### ISSUE TITLE
[10.0] Style Manager error on less  "TypeError: cannot concatenate 'str' and 'bool' objects"

### ISSUE THREAD

**Issue by zeroheure** [SythilTech/Odoo10#20]
Hello
Using both style manager 1.1 and 1.2 on Odoo 10, I can't generate less file. 
Here's the Traceback Odoo gives when I click on " Generate LESS" button :

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<string>", line 2, in generate_less
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 361, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/var/lib/odoo/addons/10.0/website_style_manager/models/website.py", line 38, in generate_less
    less_data += "@" + less_style.internal_name + ": " + less_style.value + ";\n"
TypeError: cannot concatenate 'str' and 'bool' objects

**Comment by SythilTech** [comment]
Hello,

Thank you for bring this to my attention

I have released v1.1.3 which should fix this issue.

Regards
Steven

**Comment by zeroheure** [comment]
It works now, thanks!
