### ISSUE TITLE
Error when I click on Log SaaS Server

### ISSUE THREAD

**Issue by Matt-OBell** [SythilTech/Odoo10#21]
I installed the saas server and the saas client successfully. Saas server module was installed on my server database and Saas client module was installed on the template database.

From the Saas server database, if I click on "Log SaaS Server"  under Database Manager>>Settings, I get the following errors:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 685, in call_kw
    method = getattr(type(model), name)
AttributeError: type object 'saas.settings' has no attribute 'saas_server_setting'

**Comment by SythilTech** [comment]
Thank you for bringing this to my attention.

The button seems to serve no purpose and has been removed in the latest version.

Regards
Steven

**Comment by Matt-OBell** [comment]
Thanks for the quick feedback and the update. I thought the button allows the admin to login directly to client (saas users) database directly from the server. If such a functionality is there, it will help the admin to login to a client's database without requesting for the client's password

Regards
Dare

**Comment by SythilTech** [comment]
Hi Dare,

I have released v1.0.5 of the module, this adds 2 buttons, one that logs into the super admin and the other that logs into the saas users account.

Please note that the admin login button will not work retrospectively for any client databases created prior to this update, if you have the password for the template database that will work however as of v1.0..5 the admin password of the client database gets randomised.

Regards
Steven

**Comment by Matt-OBell** [comment]
Morning Steve,

 

Thanks for the recent update. I think the main concern expressed in my previous email is probably going to be the situation with most people who want to use the SaaS modules. Clients who sign to SaaS platform initially should be offered sub-domain names for their database so that they can launch their database with xyx.saascompany.com. Some even  want to use their dedicated domains eg www.xyz.com.

In my test, I mentioned that the database gets created as ‘xyz’and after that user is re-directed to say xyz.saascompany.com. This redirection tries to find a database with the name xyz.saascompany.com and if it doesn’t, it opens the database creation form (xyz.saascompany.com/web/database/manager. This is where the issue is. It shows that there is no link between the ‘xyz’ database created and the domain xyz.saascompany.com.  The ideal situation should be that the direction to xyz.saascompany.com should launch the database ‘xyz’ but this is not the case


Regards

Dare

**Comment by Matt-OBell** [comment]
Hi Steve,

After installing v1.0.5 and I try to create a database, I get the following error message:

ProgrammingError: column saas_database.super_admin_login does not exist

LINE 1: ...in" as "login","saas_database"."state" as "state","saas_data...




Full traceback as follows:





Traceback (most recent call last):

  File "/opt/odoo/odoo/odoo/http.py", line 640, in _handle_exception

    return super(JsonRequest, self)._handle_exception(exception)

  File "/opt/odoo/odoo/odoo/http.py", line 677, in dispatch

    result = self._call_function(**self.params)

  File "/opt/odoo/odoo/odoo/http.py", line 333, in _call_function

    return checked_call(self.db, *args, **kwargs)

  File "/opt/odoo/odoo/odoo/service/model.py", line 101, in wrapper

    return f(dbname, *args, **kwargs)

  File "/opt/odoo/odoo/odoo/http.py", line 326, in checked_call

    result = self.endpoint(*a, **kw)

  File "/opt/odoo/odoo/odoo/http.py", line 935, in __call__

    return self.method(*args, **kw)

  File "/opt/odoo/odoo/odoo/http.py", line 506, in response_wrap

    response = f(*args, **kw)

  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 885, in call_kw

    return self._call_kw(model, method, args, kwargs)

  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 877, in _call_kw

    return call_kw(request.env[model], method, args, kwargs)

  File "/opt/odoo/odoo/odoo/api.py", line 689, in call_kw

    return call_kw_multi(method, model, args, kwargs)

  File "/opt/odoo/odoo/odoo/api.py", line 680, in call_kw_multi

    result = method(recs, *args, **kwargs)

  File "/opt/odoo/odoo/odoo/models.py", line 3021, in read

    values[name] = field.convert_to_read(record[name], record, use_name_get)

  File "/opt/odoo/odoo/odoo/models.py", line 5210, in __getitem__

    return self._fields[key].__get__(self, type(self))

  File "/opt/odoo/odoo/odoo/fields.py", line 870, in __get__

    self.determine_value(record)

  File "/opt/odoo/odoo/odoo/fields.py", line 982, in determine_value

    self.compute_value(recs)

  File "/opt/odoo/odoo/odoo/fields.py", line 936, in compute_value

    self._compute_value(records)

  File "/opt/odoo/odoo/odoo/fields.py", line 927, in _compute_value

    getattr(records, self.compute)()

  File "/opt/odoo/odoo/odoo/models.py", line 461, in compute_concurrency_field_with_access

    record.write_date or record.create_date or odoo.fields.Datetime.now()

  File "/opt/odoo/odoo/odoo/fields.py", line 870, in __get__

    self.determine_value(record)

  File "/opt/odoo/odoo/odoo/fields.py", line 972, in determine_value

    record._prefetch_field(self)

  File "/opt/odoo/odoo/odoo/models.py", line 3066, in _prefetch_field

    result = records.read([f.name for f in fs], load='_classic_write')

  File "/opt/odoo/odoo/odoo/models.py", line 3010, in read

    self._read_from_database(stored, inherited)

  File "/opt/odoo/odoo/odoo/models.py", line 3134, in _read_from_database

    cr.execute(query_str, params)

  File "/opt/odoo/odoo/odoo/sql_db.py", line 154, in wrapper

    return f(self, *args, **kwargs)

  File "/opt/odoo/odoo/odoo/sql_db.py", line 231, in execute

    res = self._obj.execute(query, params)

ProgrammingError: column saas_database.super_admin_login does not exist

LINE 1: ...in" as "login","saas_database"."state" as "state","saas_data...

                                                             ^

**Comment by Matt-OBell** [comment]
Just to let you know that I created a Saas Template database afresh, installed the updated saas client. On the server, I upgraded the saas server module. Then I tried to create a new database again but it did not work. Same error below

 

From: Dare Ojo-Bello | Matt O'Bell [mailto:ojo.bello@mattobell.com] 
Sent: Monday, September 4, 2017 2:11 PM
To: 'SythilTech/Odoo10'
Subject: RE: [SythilTech/Odoo10] Error when I click on Log SaaS Server (#21)

 

Hi Steve,

After installing v1.0.5 and I try to create a database, I get the following error message:

ProgrammingError: column saas_database.super_admin_login does not exist

LINE 1: ...in" as "login","saas_database"."state" as "state","saas_data...








Full traceback as follows:













Traceback (most recent call last):

  File "/opt/odoo/odoo/odoo/http.py", line 640, in _handle_exception

    return super(JsonRequest, self)._handle_exception(exception)

  File "/opt/odoo/odoo/odoo/http.py", line 677, in dispatch

    result = self._call_function(**self.params)

  File "/opt/odoo/odoo/odoo/http.py", line 333, in _call_function

    return checked_call(self.db, *args, **kwargs)

  File "/opt/odoo/odoo/odoo/service/model.py", line 101, in wrapper

    return f(dbname, *args, **kwargs)

  File "/opt/odoo/odoo/odoo/http.py", line 326, in checked_call

    result = self.endpoint(*a, **kw)

  File "/opt/odoo/odoo/odoo/http.py", line 935, in __call__

    return self.method(*args, **kw)

  File "/opt/odoo/odoo/odoo/http.py", line 506, in response_wrap

    response = f(*args, **kw)

  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 885, in call_kw

    return self._call_kw(model, method, args, kwargs)

  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 877, in _call_kw

    return call_kw(request.env[model], method, args, kwargs)

  File "/opt/odoo/odoo/odoo/api.py", line 689, in call_kw

    return call_kw_multi(method, model, args, kwargs)

  File "/opt/odoo/odoo/odoo/api.py", line 680, in call_kw_multi

    result = method(recs, *args, **kwargs)

  File "/opt/odoo/odoo/odoo/models.py", line 3021, in read

    values[name] = field.convert_to_read(record[name], record, use_name_get)

  File "/opt/odoo/odoo/odoo/models.py", line 5210, in __getitem__

    return self._fields[key].__get__(self, type(self))

  File "/opt/odoo/odoo/odoo/fields.py", line 870, in __get__

    self.determine_value(record)

  File "/opt/odoo/odoo/odoo/fields.py", line 982, in determine_value

    self.compute_value(recs)

  File "/opt/odoo/odoo/odoo/fields.py", line 936, in compute_value

    self._compute_value(records)

  File "/opt/odoo/odoo/odoo/fields.py", line 927, in _compute_value

    getattr(records, self.compute)()

  File "/opt/odoo/odoo/odoo/models.py", line 461, in compute_concurrency_field_with_access

    record.write_date or record.create_date or odoo.fields.Datetime.now()

  File "/opt/odoo/odoo/odoo/fields.py", line 870, in __get__

    self.determine_value(record)

  File "/opt/odoo/odoo/odoo/fields.py", line 972, in determine_value

    record._prefetch_field(self)

  File "/opt/odoo/odoo/odoo/models.py", line 3066, in _prefetch_field

    result = records.read([f.name for f in fs], load='_classic_write')

  File "/opt/odoo/odoo/odoo/models.py", line 3010, in read

    self._read_from_database(stored, inherited)

  File "/opt/odoo/odoo/odoo/models.py", line 3134, in _read_from_database

    cr.execute(query_str, params)

  File "/opt/odoo/odoo/odoo/sql_db.py", line 154, in wrapper

    return f(self, *args, **kwargs)

  File "/opt/odoo/odoo/odoo/sql_db.py", line 231, in execute

    res = self._obj.execute(query, params)

ProgrammingError: column saas_database.super_admin_login does not exist

LINE 1: ...in" as "login","saas_database"."state" as "state","saas_data...

                                                             ^

**Comment by SythilTech** [comment]
Hi Dare,

Please ensure you have restarted your Odoo instance just before hitting the upgrade button.

super_admin_login is a new field added in this version, a restart is required for ensure Odoo uses the updated python code.

Regards
Steven

**Comment by Matt-OBell** [comment]
Yes I did that. I even did –u all while restarting my odoo instance. I repeated it now and its not giving that error.

Thanks Steve
Dare

**Comment by Matt-OBell** [comment]
Hi Steve,

My quick observation of the two buttons you provided:

a)      When I click Admin to login to the client database, the page opens in the same tab and I am able to login. But from the client, I cannot go back to my main database (server). Even when I logout from the client database and try to login again, it is taking me back into the client database. I cannot easily login back to the portal (ie the server database)

Unless I launch the link www.mydomainname.com/web?db=mydomainname (eg http://simpoolerp.com/web?db=simpoolerp.com)

Suggest you open the page in a new tab when the 

b)  When I click on “User Login” instead of “Admin Login”, I get the webclient error “Record does not exist or it has been deleted”. Once this error occurs, nothing works in Saas anymore





The full trace back is:





Traceback (most recent call last):

  File "/opt/odoo/odoo/odoo/http.py", line 640, in _handle_exception

    return super(JsonRequest, self)._handle_exception(exception)

  File "/opt/odoo/odoo/odoo/http.py", line 677, in dispatch

    result = self._call_function(**self.params)

  File "/opt/odoo/odoo/odoo/http.py", line 333, in _call_function

    return checked_call(self.db, *args, **kwargs)

  File "/opt/odoo/odoo/odoo/service/model.py", line 101, in wrapper

    return f(dbname, *args, **kwargs)

  File "/opt/odoo/odoo/odoo/http.py", line 326, in checked_call

    result = self.endpoint(*a, **kw)

  File "/opt/odoo/odoo/odoo/http.py", line 935, in __call__

    return self.method(*args, **kw)

  File "/opt/odoo/odoo/odoo/http.py", line 506, in response_wrap

    response = f(*args, **kw)

  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 827, in search_read

    return self.do_search_read(model, fields, offset, limit, domain, sort)

  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 846, in do_search_read

    Model = request.env[model]

  File "/opt/odoo/odoo/odoo/api.py", line 760, in __getitem__

    return self.registry[model_name]._browse((), self)

  File "/opt/odoo/odoo/odoo/modules/registry.py", line 174, in __getitem__

    return self.models[model_name]

KeyError: u'saas.database'

**Comment by SythilTech** [comment]
Hi Dare,

Unfortunately opening a new tab does not retain the old login session, currently I haven't seen any working examples of having multiple login sessions at the same time, if you happen to find one I'll gladly introduce it.

Yes this does mean you will have to re-login back to saas database after you have finished making changes in a saas clients database, you can quickly to back using the url you specified.

Regards
Steven

**Comment by Matt-OBell** [comment]
As I am testing, I indeed have that situation and that is why I reported it. In practical situation, this may not be the case but it is also possible to open a tab as admin and then open another tab to login to a client database. This will be a high possibility where support is provided to clients by logging into their databases



Dare

**Comment by Matt-OBell** [comment]
Hello Steve,

Any update to the email below?


Regards

Dare



From: Dare Ojo-Bello | Matt O'Bell [mailto:ojo.bello@mattobell.com] 
Sent: Monday, September 4, 2017 9:20 AM
To: 'SythilTech/Odoo10'
Subject: RE: [SythilTech/Odoo10] Error when I click on Log SaaS Server (#21)

 

Morning Steve,

 

Thanks for the recent update. I think the main concern expressed in my previous email is probably going to be the situation with most people who want to use the SaaS modules. Clients who sign to SaaS platform initially should be offered sub-domain names for their database so that they can launch their database with xyx.saascompany.com. Some even  want to use their dedicated domains eg www.xyz.com.

In my test, I mentioned that the database gets created as ‘xyz’and after that user is re-directed to say xyz.saascompany.com. This redirection tries to find a database with the name xyz.saascompany.com and if it doesn’t, it opens the database creation form (xyz.saascompany.com/web/database/manager. This is where the issue is. It shows that there is no link between the ‘xyz’ database created and the domain xyz.saascompany.com.  The ideal situation should be that the direction to xyz.saascompany.com should launch the database ‘xyz’ but this is not the case


Regards

Dare

**Comment by Matt-OBell** [comment]
Dear Steve,

I have tried to test the two buttons severally using a newly created template and client databases after you released the version 1.0.5. While logged in as admin on the server, If I open a client database form from SaaS Databases, and then click on Admin Login or User Login, it launches the url for the client database in the same window. But neither the Server admin password or the template admin password works when I tried to login to the client database.

My suggestion:

a) From the server, when we click on Admin Login or User Login, the link should open in a new tab
b) When Admin Login is clicked, it should allow Admin to launch into the client database and see all features as Super User
c) When User Login is clicked, it should allow the user logged into the server to only see limited features available to the SaaS owner (ie client)

Let me know what you think
Dare

**Comment by Matt-OBell** [comment]
Hi Steve,

How is the weekend. I really need your help this morning. I have installed a module in my template to prevent saas users from installing modules. After the setup, I also need to install additional modules which were not added in the template. If I am able to login to the template, this should not be a problem.

If you can help with the points raised in my last email so that I can access client databases as a super user, I will really appreciate.

Regards

Dare

 

From: Dare Ojo-Bello | Matt O'Bell [mailto:ojo.bello@mattobell.com] 
Sent: Friday, September 22, 2017 3:19 PM
To: 'SythilTech/Odoo10'; 'SythilTech/Odoo10'
Cc: 'Matt-OBell'; 'Author'
Subject: RE: [SythilTech/Odoo10] Error when I click on Log SaaS Server (#21)

 

Dear Steve,

I have tried to test the two buttons severally using a newly created template and client databases after you released the version 1.0.5. While logged in as admin on the server, If I open a client database form from SaaS Databases, and then click on Admin Login or User Login, it launches the url for the client database in the same window. But neither the Server admin password or the template admin password works when I tried to login to the client database.

My suggestion:

a) From the server, when we click on Admin Login or User Login, the link should open in a new tab
b) When Admin Login is clicked, it should allow Admin to launch into the client database and see all features as Super User
c) When User Login is clicked, it should allow the user logged into the server to only see limited features available to the SaaS owner (ie client)

Let me know what you think
Dare

**Comment by SythilTech** [comment]
Hi Dare,

I will look into the login buttons not working as intended, in the mean time you can view the randomly generated admin credentials by editing you saas database form view to show the randomly generated password.

<field name="super_admin_login"/>
<field name="super_admin_password"/>

If that doesn't work you can do a password reset for the admin account via these instructions
https://github.com/odoo/odoo/issues/9806


a) I will look into opening the login into a new tab, this will require a bit of investigation due to the way sessions work in Odoo but I will see if it is possible.
b & c) Yes this is how it is designed to work  minus the bug which is causing it not to function.


Regards
Steven

**Comment by Matt-OBell** [comment]
Hi Steve,
Thanks for the reply. What is the username for the admin in the client database. Ie the database I created from the template?. Normally the admin user is not displayed to the saas user. What is the admin user name (login) so I can try to change the password

Dare

**Comment by SythilTech** [comment]
Hi Dare,

The admin username is the one you entered when you created the template database.

You can also see the admin login and password by added these fields to the saas database form view.
<pre><field name="super_admin_login"/></pre>
<pre><field name="super_admin_password"/></pre>

Regards
Steven
