### ISSUE TITLE
error prevent installation in odoo 10

### ISSUE THREAD

**Issue by Salmon-Bard** [SythilTech/Odoo10#6]
I'm getting the flollowing error while trying to install in oddo 10
`Discuss
Calendar
Sales
Pathology Management
Purchases
Inventory
Invoicing
Website
Website Admin
Apps
Settings
 Administrator (odoo2) 
 

Apps
App Store
Updates
Update Apps List
Apply Scheduled Upgrades
Powered by Odoo
Apps
Module
html

Search...
 Filters   Group By   Favorites 
1-1 / 1  

HTML Form Builder
Manage both internal and external forms
html_form_builder
Install
×
Odoo
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 842, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 894, in convert_csv_import
    result = env[model].load(fields, datas)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 752, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 170, in __getitem__
    return self.models[model_name]
KeyError: u'html.form.snippet.action'`

**Comment by SythilTech** [comment]
Hello,

Sorry I am not able to replicate this issue, the html.form.snippet.action model  was created from my tests.

Please get the latest copy of the module (1.0.10) and try again on a fresh database.

You will need to restart your Odoo instance before reinstalling/upgrading for the code changes to take effect.

Regards
Steven
