### ISSUE TITLE
[10.0][HTML form builder] Get error when create a submit action

### ISSUE THREAD

**Issue by arthur38** [SythilTech/Odoo10#8]
I get this error when I create a submit action to my form:

Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 5460, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 5359, in _onchange_eval
    process(method_res)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 5336, in process
    if res.get('value'):
AttributeError: 'list' object has no attribute 'get'

Thanks in advance for your reply.

**Comment by SythilTech** [comment]
Hello,

My records show this issue was fixed in version 1.0.1 of the module, can you please update the module to the latest version (v1.0.10) and retry.

You will need to restart your Odoo instance before upgrading the module for code changes to take effect.

Regards
Steven

**Comment by arthur38** [comment]
yeah it works !

Thanks
