### ISSUE TITLE
[10.0][html_form_builder] Binary fields in input group

### ISSUE THREAD

**Issue by arthur38** [SythilTech/Odoo10#9]
Hi,

In my works, I have to display a binary fields in a input group but it seems to be impossible currently.
Do you think is it possible ?

Best regards.

Arthur Bonnel.

**Comment by SythilTech** [comment]
Hi Arthur,

Currently it is not possible.

I'll see about introducing it as a new feature.

It might be awhile though since I currently have a significant backlog of work but will get back to you when I have finished it.

Regards
Steven

**Comment by SythilTech** [comment]
Hi Authur,

I have released a new version of the module (1.0.11) which supports binary fields in input groups.

There is 1 quirk though, the module will try to place the filename of the uploaded binary file in a field with the _filename extension

e.g. if the binary field is called "image" it will put the filename in "image_filename"

If "<field_name>_filename" does not exist it may be difficult to open the file since it will lack a file extension (.jpg, .png).

Regards
Steven

**Comment by arthur38** [comment]
Hi Steven,

Thanks very much for your reply and the released.
I've installed the new version and tried it and like you said, i have a problem with the filename.

it put's me 'false' in the file name.

And i have an other problem, when i submit the form without specify the input group, it put's me this error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/opt/odoo/odoo-10.0/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 1471, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/odoo-10.0/addons/website/models/ir_http.py", line 210, in _dispatch
    resp = super(Http, cls)._dispatch()
  File "/opt/odoo/odoo-10.0/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/odoo-10.0/addons/website/models/ir_http.py", line 262, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/html_form_builder/controllers/main.py", line 633, in my_secure_insert
    return self.process_form(kwargs)
  File "/opt/odoo/odoo-10.0/addons/html_form_builder/controllers/main.py", line 572, in process_form
    field_valid = action(fi, values[fi.html_name], values)
  File "/opt/odoo/odoo-10.0/addons/html_form_builder/controllers/main.py", line 658, in _process_html_input_group
    row[ str(sub_field.name) + "_filename"] = values[row[sub_field.name]].filename
KeyError: u'datas

datas is the field name of my binary field.

i will work on this 2 error, i get back to you if i solved them.

Thanks again.

Regards
Arthur

**Comment by SythilTech** [comment]
Hi Arthur,

Thank you for quickly bringing this to my attention.
I have released a new version which fixes the issue where an error would occur if the input group was empty.

Regards

**Comment by arthur38** [comment]
Hi Steven,

It works great for me Thanks ! Good job !

I get back to you if i have other issues or suggestions.

Regards
